name: Deploy the app
# Deploy to a staging environment

on: 
  pull_request: 
    types: [labeled]

env: 
  IMAGE_REGISTRY_URL: ghcr.io
  DOCKER_IMAGE_NAME: SudheerKumarP0357-azure-ttt
  AZURE_WEBAPP_NAME: SudheerKumarP0357-ttt-app

jobs: 
  build: 
    if: contains(github.event.pull_request.labels.*.name, 'stage' )

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-node@v4.0.2
        with: 
          node-version: 16
      - name: npm install and build webpack
        run: |
          npm install webpack@5 --save-dev
          npm run build
      - uses: actions/upload-artifact@v4.3.1
        with: 
          name: webpack artifacts
          path: public/
  
  Build-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    name: Build image and store in Github Container Registry
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Download build artifact
        uses: actions/download-artifact@v4.1.4
        with: 
          name: webpack artifacts
          path: public/

      - name: Login to Github Container Registry [GHCR]
        uses: docker/login-action@v3.1.0
        with: 
          registry: ${{ env.IMAGE_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with: 
          images: ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.DOCKER_IMAGE_NAME}}
          tags: |
            type=sha,formate=long,prefix=

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5.3.0
        with: 
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: $ {{ steps.meta.outputs.labels }}

  Deploy-to-Azure:
    runs-on: ubuntu-latest
    needs: Build-Docker-Image
    name: Deploy app container to Azure
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v2.0.0
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: azure/docker-login@v1
        with: 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}
          login-server: ${{env.IMAGE_REGISTRY_URL}} 

      - name: Deploy web app container
        uses: azure/webapps-deploy@v3.0.0
        with:  
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}

      - name: Azure logout via Azure CLI
        uses: azure/cli@v2.0.0
        with: 
          inlineScript: |
            az logout
            az cache purge
            az account clear
          
  
